### ISSUE TITLE
关于数据集的一些请教。

### ISSUE THREAD

**Issue by GuanHY** [Tsunami-kun/BimanGrasp-Dataset#1]
您好，我看了您提供的数据集，似乎是所有的物体均在一个文件夹里面，这个数据集是针对GSO数据集使用BimanGrasp收集到的成功样本吗？还是包含了其他数据集的，比如DDG,YCB等您通过BimanGrasp-DDPM后期生成的样本？
另外，想问一下您是否能提供BimanGrasp-DDPM部分的训练、评估代码？因为我前期也做了一些双手抓取的工作，想参考一下或者说作为baseline比较一下。

**Comment by Tsunami-kun** [comment]
GuanHY您好，

感谢您的问题。这里是解答：

> **1. 这个数据集是针对GSO数据集使用BimanGrasp收集到的成功样本吗？还是包含了其他数据集的，比如DDG, YCB等您通过BimanGrasp-DDPM后期生成的样本？**

本次release的BimanGrasp-Dataset-v1主要为GSO的抓取数据，也包含了部分来自DDG， YCB和ContactDB的样本，共计991个物体的双手抓取。

我在Dataset-v1中删除了GPT4-Vision验证分数为1分和2分（见Sec. IV. A.第二段）的GSO抓取数据。此外，为了让数据集更全面完善，我又生成了DDG， YCB和ContactDB物体（约100个）的双手抓取。这一版本数据集新增的抓取，也是由优化算法生成。

> **2. 想问一下您是否能提供BimanGrasp-DDPM部分的训练、评估代码？**

感谢建议。我们会考虑发布BimanGrasp-DDPM的代码。也会考虑用Dataset-v1重新训练，并且建立新的评估基准，比如用扫描实物和Objaverse的物体进行测试。可以关注我们的后续更新 :)

**Comment by GuanHY** [comment]
好的。感谢！
